export const UPLOAD_IMAGE_START='UPLOAD_IMAGE_START'
export const UPLOAD_IMAGE_SUCCESS='UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAIL='UPLOAD_IMAGE_FAIL'

export const FAVOURITE_IMAGE_START='FAVOURITE_IMAGE_START'
export const FAVOURITE_IMAGE_SUCCESS='FAVOURITE_IMAGE_SUCCESS'
export const FAVOURITE_IMAGE_FAIL='FAVOURITE_IMAGE_FAIL'
export const UNFAVOURITE_IMAGE_START='UNFAVOURITE_IMAGE_START'
export const UNFAVOURITE_IMAGE_SUCCESS='UNFAVOURITE_IMAGE_SUCCESS'
export const UNFAVOURITE_IMAGE_FAIL='UNFAVOURITE_IMAGE_FAIL'


export const LIKE_IMAGE_START='LIKE_IMAGE_START'
export const LIKE_IMAGE_SUCCESS='LIKE_IMAGE_SUCCESS'
export const LIKE_IMAGE_FAIL='LIKE_IMAGE_FAIL'
export const UNLIKE_IMAGE_START='UNLIKE_IMAGE_START'
export const UNLIKE_IMAGE_SUCCESS='UNLIKE_IMAGE_SUCCESS'
export const UNLIKE_IMAGE_FAIL='UNLIKE_IMAGE_FAIL'